### ISSUE TITLE
Voxels holes/bug

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg-engine#27]
In some rare case (I'm not able to reproduce) the terrain is messed up in certain patches 

<img width="864" alt="image" src="https://github.com/aresrpg/aresrpg-engine/assets/11330271/59a63de2-7824-4ca5-a7ea-456834dd3dcc">

**Comment by Sceat** [comment]
@piellardj it seems to be happening also in latest version 

![Image](https://github.com/aresrpg/aresrpg-engine/assets/11330271/2e6a8a9c-5956-4b33-a264-23b370afc57f)

**Comment by piellardj** [comment]
Arf :(.

I don't understand what is happening. I will reread the shaders code.

I haven't seen these holes on my machine for a while. If you reload the game, are they always in the same spots or is it random ?

**Comment by piellardj** [comment]
Debugging GPU stuff is very tricky, sometimes it depends on drivers etc.

If I fail to fix this, another option I might explore would be to make the mesh generation on CPU-side in a separate thread. It will be more robust / more easily debuggable for sure. It might be slower tho.

**Comment by Sceat** [comment]
it usually works, it's pretty random and at different positions each time. It's not that urgent as we can still play, if it's OS/hardware specific then it'll be quite hard to debug for now, let's not make it a priority :/ @DeltaEvo might be of help here

**Comment by Sceat** [comment]
![Image](https://github.com/aresrpg/aresrpg-engine/assets/11330271/c8ddfa3d-f8bd-42b2-9607-6b6cc123622b)



![Image](https://github.com/aresrpg/aresrpg-engine/assets/11330271/7b9685d6-c0f7-446b-b195-1cf89a9c097b)

**Comment by Sceat** [comment]
Fixed with the CPU engine
