### ISSUE TITLE
LOD holes

### ISSUE THREAD

**Issue by Sceat** [aresrpg/aresrpg-engine#28]
It seems when we are far high, there can be holes in the LOD
<img width="890" alt="image" src="https://github.com/aresrpg/aresrpg-engine/assets/11330271/7818f02f-5324-480d-87f0-439eeb48472e">

**Comment by StonyTV** [comment]
If it ever helps, this is what I noticed

Z: 18

![image](https://github.com/aresrpg/aresrpg-engine/assets/20698024/0a3913ce-89cb-459e-9c7a-52dca39172f2)

Z: 17

![image](https://github.com/aresrpg/aresrpg-engine/assets/20698024/4a50c533-0943-4c78-b5a2-6dc906b04fed)

Z: 16

![image](https://github.com/aresrpg/aresrpg-engine/assets/20698024/228f22ef-e925-4867-b037-80775e29c5d6)

**Comment by piellardj** [comment]
Merci pour le signalement, effectivement j'ai vu ça. Je comprends pourquoi ces trous sont là, j'ai un fix en tête, qui devrait en plus accélerer le calcul des voxels.
